Stereo:
  F:
  - - -2.2444469927642867e-05
    - -0.00025175231394485335
    - 0.08937998821408677
  - - 0.0002852822326464619
    - -1.668008144751965e-05
    - -0.1448699409804013
  - - -0.08225369135507579
    - 0.13711232139012144
    - 1.0
  H1:
  - - 0.09279441941881578
    - 0.07137702267595356
    - -97.32672278873736
  - - 0.2391627266497809
    - -0.08872941314431759
    - -98.41676764309345
  - - 0.000752940847578357
    - 0.00024070606770808332
    - -0.47009294165738047
  H2:
  - - -0.4059403464444038
    - -0.17905763350323967
    - 492.87474290298667
  - - -1.394241277090482
    - 0.4779701467892114
    - 571.4443734395434
  - - -0.004127769352357813
    - -0.0018207320813370205
    - 2.757861892275385
Type: Uncalibrated
